// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2876.Steamworks2017.subsystems;

import org.usfirst.frc2876.Steamworks2017.RobotMap;
import org.usfirst.frc2876.Steamworks2017.commands.ClimberStop;

import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.command.Subsystem;

/**
 *
 */
public class Climber extends Subsystem {

	CANTalon climberTalon = RobotMap.climberClimberTalon;
	CANTalon slaveTalon = RobotMap.climberSlaveTalon;
	
//	slaveTalon.changeControlMode(CANTalon.TalonControlMode.Follower);
//	slaveTalon.set(climberTalon.getDeviceID());


    public void initDefaultCommand() {

    	setDefaultCommand(new ClimberStop());
    }
    public void climberStart(){
    	climberTalon.set(-1);
    }
    public void climberStop(){
    	climberTalon.set(0);
    }
   
}
