// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2876.Steamworks2017.subsystems;

import org.usfirst.frc2876.Steamworks2017.RobotMap;

import org.usfirst.frc2876.Steamworks2017.commands.*;

import edu.wpi.first.wpilibj.I2C;
import edu.wpi.first.wpilibj.I2C.Port;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

/**
 *
 */
public class Vision extends Subsystem {

	public PixyI2C gearPixy;
	public PixyI2C boilerPixy;
	Port port = Port.kOnboard;
	String print;
	public PixyPacket[] packet1 = new PixyPacket[7];
	public PixyPacket[] packet2 = new PixyPacket[7];

	public Vision() {
		gearPixy = new PixyI2C("gear", new I2C(port, 0x54), packet1, new PixyException(print), new PixyPacket());
		boilerPixy = new PixyI2C("boiler", new I2C(port, 0x55), packet2, new PixyException(print), new PixyPacket());
	}

	public void initDefaultCommand() {
		// TODO: Should we add a PixyIdle command? What should it do? Nothing?
		// Might be useful to have it call some function to get target and print
		// to dashboard? Eh.. if robot isn't aimed at the target we get nothing.
	}

	public void testGearPixy() {
		for (int i = 0; i < packet1.length; i++)
			packet1[i] = null;
		SmartDashboard.putString("gearPixy hello", "working");
		for (int i = 1; i < 8; i++) {
			try {
				packet1[i - 1] = gearPixy.readPacket(i);
			} catch (PixyException e) {
				SmartDashboard.putString("gearPixy Error: " + i, "exception");
			}
			if (packet1[i - 1] == null) {
				SmartDashboard.putString("gearPixy Error: " + i, "True");
				continue;
			}
			SmartDashboard.putNumber("gearPixy X Value: " + i, packet1[i - 1].X);
			SmartDashboard.putNumber("gearPixy Y Value: " + i, packet1[i - 1].Y);
			SmartDashboard.putNumber("gearPixy Width Value: " + i, packet1[i - 1].Width);
			SmartDashboard.putNumber("gearPixy Height Value: " + i, packet1[i - 1].Height);
			SmartDashboard.putString("gearPixy Error: " + i, "False");
		}
	}

	public void testBoilerPixy() {
		for (int i = 0; i < packet2.length; i++)
			packet2[i] = null;
		SmartDashboard.putString("boilerPixy hello", "working");
		for (int i = 1; i < 8; i++) {
			try {
				packet2[i - 1] = boilerPixy.readPacket(i);
			} catch (PixyException e) {
				SmartDashboard.putString("boilerPixy Error: " + i, "exception");
			}
			if (packet2[i - 1] == null) {
				SmartDashboard.putString("boilerPixy Error: " + i, "True");
				continue;
			}
			SmartDashboard.putNumber("boilerPixy X Value: " + i, packet2[i - 1].X);
			SmartDashboard.putNumber("boilerPixy Y Value: " + i, packet2[i - 1].Y);
			SmartDashboard.putNumber("boilerPixy Width Value: " + i, packet2[i - 1].Width);
			SmartDashboard.putNumber("boilerPixy Height Value: " + i, packet2[i - 1].Height);
			SmartDashboard.putString("boilerPixy Error: " + i, "False");
		}

	}

	// Get blocks that represent the vision tape on either side of the peg. This
	// can return 0,1, or 2 blocks depending what is found in a frame.
	public PixyPacket[] getPegPosition() {
		PixyPacket[] blocks = gearPixy.readBlocks();
		SmartDashboard.putBoolean("Peg Blocks Array is null", blocks == null);
		if (blocks == null)
			return null;
		SmartDashboard.putString("Peg Block 0", (blocks[0] == null) ? "null" : blocks[0].toString());
		SmartDashboard.putString("Peg Block 1", (blocks[1] == null) ? "null" : blocks[1].toString());
		return blocks;
	}

	// Using blocks from pixy, create a target class that will do all the magic
	// math we need to determine angle and distance to peg.
	public GearTarget getGearTarget() {
		PixyPacket[] packets = getPegPosition();
		if (packets == null || (packets[0] == null && packets[1] == null))
			return null;
		return new GearTarget(packets[0], packets[1]);
	}

	public GearTarget getGearTargetFiltered() {
		for (int i = 0; i < 5; i++) {
			GearTarget t = getGearTarget();
			if (t != null) {
				return t;
			}
		}
		return null;
	}
}
