// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2876.Steamworks2017;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.PWMSpeedController;
import edu.wpi.first.wpilibj.Relay;
// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveTrainFrontLeftTalon;
    public static CANTalon driveTrainFrontRightTalon;
    public static CANTalon driveTrainRearLeftTalon;
    public static CANTalon driveTrainRearRightTalon;
    public static Relay driveTrainLightSpike;
    public static Encoder driveTrainLeftEncoder;
    public static Encoder driveTrainRightEncoder;
    public static CANTalon shooterTalon;
    public static CANTalon fuelTankAgitator;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon intakeIntakeTalon;
    public static CANTalon climberClimberTalon;

    // public static CANTalon climberSlaveTalon;
    
    public static PWMSpeedController lightSpike;

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainFrontLeftTalon = new CANTalon(4);
        LiveWindow.addActuator("DriveTrain", "FrontLeftTalon", driveTrainFrontLeftTalon);
        
        driveTrainFrontRightTalon = new CANTalon(2);
        LiveWindow.addActuator("DriveTrain", "FrontRightTalon", driveTrainFrontRightTalon);
        
        driveTrainRearLeftTalon = new CANTalon(3);
        LiveWindow.addActuator("DriveTrain", "RearLeftTalon", driveTrainRearLeftTalon);
        
        driveTrainRearRightTalon = new CANTalon(1);
        LiveWindow.addActuator("DriveTrain", "RearRightTalon", driveTrainRearRightTalon);
        
        driveTrainLightSpike = new Relay(0);
        LiveWindow.addActuator("DriveTrain", "LightSpike", driveTrainLightSpike);
        
        driveTrainLeftEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "LeftEncoder", driveTrainLeftEncoder);
        driveTrainLeftEncoder.setDistancePerPulse(1.0);
        driveTrainLeftEncoder.setPIDSourceType(PIDSourceType.kRate);
        driveTrainRightEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "RightEncoder", driveTrainRightEncoder);
        driveTrainRightEncoder.setDistancePerPulse(1.0);
        driveTrainRightEncoder.setPIDSourceType(PIDSourceType.kRate);
        shooterTalon = new CANTalon(6);
        LiveWindow.addActuator("Shooter", "Talon", shooterTalon);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        intakeIntakeTalon = new CANTalon(7);
        climberClimberTalon = new CANTalon(5);

        //        climberSlaveTalon = new CANTalon(0);
        
        fuelTankAgitator = new CANTalon(8);
        lightSpike = new PWMSpeedController(0){
        	
        };
    }
}
