// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc2876.Steamworks2017.commands;

import edu.wpi.first.wpilibj.Relay.Value;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2876.Steamworks2017.Robot;
import org.usfirst.frc2876.Steamworks2017.RobotMap;
import org.usfirst.frc2876.Steamworks2017.subsystems.GearTarget;

/**
 *
 */
public class AutoAlignDriveToCenterPeg extends Command {

	int counter;
	boolean didWeFindTarget;
	double distance;

	public AutoAlignDriveToCenterPeg() {
		// This is suppose to turn to the peg
		// TODO - rename this class
		requires(Robot.driveTrain);
		requires(Robot.vision);
	}

	// Called just before this Command runs the first time
	protected void initialize() {
		counter = 0;
		RobotMap.driveTrainLightSpike.set(Value.kForward);
		didWeFindTarget = false;
		for(int i = 0; i < 10; i++){
			GearTarget t = Robot.vision.getGearTarget();
			if (t != null){ 
				distance = t.distance();
				Robot.driveTrain.startTurn(t.angle());
				SmartDashboard.putString("Gear Target t", t.toString());
				break;
			}
		}
		didWeFindTarget = true;
	}

	// Called repeatedly when this Command is scheduled to run
	protected void execute() {
		GearTarget t = Robot.vision.getGearTarget();
		if (t == null) {
			SmartDashboard.putString("GTExecStatus", "null " + ++counter);
		} else {
			SmartDashboard.putString("GTExec", t.toString());
			SmartDashboard.putString("GTExecStatus", "ok");
		}
		if (Robot.driveTrain.isTurnDone() == true) {
			Robot.driveTrain.stopTurn();
			if (Robot.driveTrain.isDistanceRunning() == false) {
				Robot.driveTrain.startDistance(distance);
			}
		}
	}

	// Make this return true when this Command no longer needs to run execute()
	protected boolean isFinished() {
		if (didWeFindTarget == false) {
			return false;
		}
		if (Robot.driveTrain.isTurnDone() == true && Robot.driveTrain.isDistanceDone()) {
			return true;
		}
		return false;
	}

	// Called once after isFinished returns true
	protected void end() {
		Robot.driveTrain.stopTurn();
		GearTarget t = Robot.vision.getGearTarget();
		if (t == null) {
			SmartDashboard.putString("Gear Target is", "null");
		} else {
			SmartDashboard.putString("Gear Target", t.toString());
			SmartDashboard.putString("Gear Target is", "ok");

		}
	}

	// Called when another command which requires one or more of the same
	// subsystems is scheduled to run
	protected void interrupted() {
		end();
	}
}
